Provider: Yaml

MySql:
  Host: "127.0.0.1"
  Port: "3306"
  Database: "surveysystem"
  User: "root"
  Password: "biden2020"

MongoDB:
  Uri: "URI_LINK"
  Database: "surveysystem"

Commands:
  Survey:
    Name: "survey"
    Description: "Vote for running surveys"
    Aliases: [ "poll" ]
  Surveyadmin:
    Name: "surveyadmin"
    Description: "Manage all surveys"
    Permission: "survey.command.surveyadmin"
    Aliases: [ "sadmin" ]
